# Generated by Django 4.2.2 on 2023-06-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='activated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='fb_profile',
            field=models.CharField(null=True),
        ),
    ]
