# Generated by Django 4.2.2 on 2023-06-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_alter_user_reg_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='profile_pic',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
