# Generated by Django 4.2.2 on 2023-06-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_num', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=16)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('birth_date', models.DateField()),
                ('fb_profile', models.CharField()),
                ('activated', models.BooleanField()),
            ],
        ),
    ]
