# Generated by Django 4.2.2 on 2023-06-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('egy_phone_number', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('profile_pic', models.ImageField(upload_to='photos/')),
                ('birth_date', models.DateField(null=True)),
                ('fb_profile', models.CharField(null=True)),
                ('activated', models.BooleanField(null=True)),
                ('activation_key', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
