# Generated by Django 4.2.2 on 2023-06-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0006_alter_user_reg_phone_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_reg',
            old_name='phone_num',
            new_name='egy_Phone_number',
        ),
    ]
