# Generated by Django 4.2.2 on 2023-06-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0007_rename_phone_num_user_reg_egy_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_reg',
            old_name='egy_Phone_number',
            new_name='egy_phone_number',
        ),
    ]
