# Generated by Django 4.2.2 on 2023-06-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0010_alter_user_reg_egy_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='egy_phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
