# Generated by Django 4.2.2 on 2023-06-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0011_alter_user_reg_egy_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
